# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=false

# minecraft
minecraft_version=1.12.2

# forge
forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12

fancy_gradle_version=1.1.+
mod_publish_gradle_version=2.0.0

# mixin
mixin_gradle_version=0.7.+
mixin_version=0.8.7
mixin_extras_version=0.5.5

# mod
mod_id=unhideflags
mod_name=UnHideFlags
mod_version=1.0.0
mod_author=["Nischhelm"]
mod_description=Disables HideFlags NBT not showing item stats
mixin_loader_class=unhideflags.UnHideFlagsPlugin

# dependencies
fermiumbooter_version=968474:8683582

# publishing (git push a commit with a new version as tag to trigger this)
# need to add repo env variables CURSEFORGE_TOKEN from https://authors.curseforge.com/account/api-tokens
# and/or MODRINTH_TOKEN from https://modrinth.com/settings/pats
# leave empty/set to false to skip
publish_to_github=false
curseforge_project_id=1171690
modrinth_project_id=Ix5TfFNi